export { useScriptTriggerConsent, useScriptEventPage, useScriptTriggerElement, useScript, useScriptGoogleAnalytics, useScriptPlausibleAnalytics, useScriptCrisp, useScriptClarity, useScriptCloudflareWebAnalytics, useScriptVercelAnalytics, useScriptPostHog, useScriptFathomAnalytics, useScriptMatomoAnalytics, useScriptMixpanelAnalytics, useScriptBingUet, useScriptGoogleTagManager, useScriptGoogleAdsense, useScriptGoogleRecaptcha, useScriptGoogleSignIn, useScriptSegment, useScriptMetaPixel, useScriptXPixel, useScriptTikTokPixel, useScriptIntercom, useScriptHotjar, useScriptStripe, useScriptLemonSqueezy, useScriptVimeoPlayer, useScriptYouTubePlayer, useScriptGoogleMaps, useScriptNpm, useScriptUmamiAnalytics, useScriptSnapchatPixel, useScriptRybbitAnalytics, useScriptDatabuddyAnalytics, useScriptRedditPixel, useScriptPayPal, useScriptGravatar, useScriptAhrefsAnalytics, useScriptLinkedInInsight, useScriptCalendly, useScriptUsercentrics, useScriptSpeedCurve } from '#app/composables/script-stubs';
export { isVue2, isVue3 } from 'vue-demi';
export { defineNuxtLink } from '#app/components/nuxt-link';
export { useNuxtApp, tryUseNuxtApp, defineNuxtPlugin, definePayloadPlugin, useRuntimeConfig, defineAppConfig } from '#app/nuxt';
export { useAppConfig, updateAppConfig } from '#app/config';
export { defineNuxtComponent } from '#app/composables/component';
export { useAsyncData, useLazyAsyncData, useNuxtData, refreshNuxtData, clearNuxtData, createUseAsyncData } from '#app/composables/asyncData';
export { useHydration } from '#app/composables/hydrate';
export { callOnce } from '#app/composables/once';
export { useState, clearNuxtState } from '#app/composables/state';
export { clearError, createError, isNuxtError, showError, useError } from '#app/composables/error';
export { useFetch, useLazyFetch, createUseFetch } from '#app/composables/fetch';
export { $fetch } from '#build/fetch.mjs';
export { useCookie, refreshCookie } from '#app/composables/cookie';
export { onPrehydrate, prerenderRoutes, useRequestHeader, useRequestHeaders, useResponseHeader, useRequestEvent, useRequestFetch, setResponseStatus } from '#app/composables/ssr';
export { onNuxtReady } from '#app/composables/ready';
export { preloadComponents, prefetchComponents, preloadRouteComponents } from '#app/composables/preload';
export { abortNavigation, addRouteMiddleware, defineNuxtRouteMiddleware, setPageLayout, navigateTo, useRoute, useRouter } from '#app/composables/router';
export { isPrerendered, loadPayload, preloadPayload, definePayloadReducer, definePayloadReviver } from '#app/composables/payload';
export { useLoadingIndicator } from '#app/composables/loading-indicator';
export { getAppManifest, getRouteRules } from '#app/composables/manifest';
export { reloadNuxtApp } from '#app/composables/chunk';
export { useRequestURL } from '#app/composables/url';
export { usePreviewMode } from '#app/composables/preview';
export { useLayout } from '#app/composables/layout';
export { useRouteAnnouncer } from '#app/composables/route-announcer';
export { useAnnouncer } from '#app/composables/announcer';
export { useRuntimeHook } from '#app/composables/runtime-hook';
export { useHead, useHeadSafe, useServerHeadSafe, useServerHead, useSeoMeta, useServerSeoMeta, injectHead } from '#app/composables/head';
export { onBeforeRouteLeave, onBeforeRouteUpdate, useLink } from 'vue-router';
export { withCtx, withDirectives, withKeys, withMemo, withModifiers, withScopeId, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onServerPrefetch, onUnmounted, onUpdated, computed, customRef, isProxy, isReactive, isReadonly, isRef, markRaw, proxyRefs, reactive, readonly, ref, shallowReactive, shallowReadonly, shallowRef, toRaw, toRef, toRefs, triggerRef, unref, watch, watchEffect, watchPostEffect, watchSyncEffect, onWatcherCleanup, isShallow, effect, effectScope, getCurrentScope, onScopeDispose, defineComponent, defineAsyncComponent, resolveComponent, getCurrentInstance, h, inject, hasInjectionContext, nextTick, provide, toValue, useModel, useAttrs, useCssModule, useSlots, useTransitionState, useId, useTemplateRef, useShadowRoot, useCssVars, Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue';
export { requestIdleCallback, cancelIdleCallback } from '#app/compat/idle-callback';
export { setInterval } from '#app/compat/interval';
export { definePageMeta, PageMeta } from '#app/composables/pages';
export { defineLazyHydrationComponent } from '#app/composables/lazy-hydration';
export { POINTS_PER_STATION, getStationPosition, getStationVisual, ADVENTURE_START_POINT, useAdventure, AdventureStation, StationVisual } from '../composables/useAdventure';
export { useAuth } from '../composables/useAuth';
export { useForceEndRound } from '../composables/useForceEndRound';
export { useJourney, JourneyStation } from '../composables/useJourney';
export { useMemberApi, MemberRecord, IdentityValues, DemographicValues, JourneyEntry, ScoreEntry, RoundRewardStatus, RoundEntry, RoundStartPayload, SurveyEntry, SubmitSurveyPayload, StationRecord, VerifyStationQrResponse, SideQuestRecord, CompletePhotoQuestPayload, SubmitAnswerPayload, RemoteStationAnswer, RoundScoreStation, MissionInputPayload, SubmitMissionAnswerPayload, SubmitMultiMissionPayload, VerifyMissionQrPayload, CheckinPayload } from '../composables/useMemberApi';
export { useOfflineAnswerSync } from '../composables/useOfflineAnswerSync';
export { useOfflineMissionAnswerSync, PendingMissionAnswer } from '../composables/useOfflineMissionAnswerSync';
export { isBrowserOffline, useOfflineMode, OfflineStationLog, OfflineRoundData } from '../composables/useOfflineMode';
export { useOfflinePhotoQuestSync } from '../composables/useOfflinePhotoQuestSync';
export { useOfflineSync, PendingCheckin, SyncResultReason, SyncResult } from '../composables/useOfflineSync';
export { usePhotoQuest } from '../composables/usePhotoQuest';
export { useProfile } from '../composables/useProfile';
export { useQrScanner, QrScanState } from '../composables/useQrScanner';
export { judgeAnswer, useQuestion } from '../composables/useQuestion';
export { useRequireProfile } from '../composables/useRequireProfile';
export { useReward } from '../composables/useReward';
export { useRound } from '../composables/useRound';
export { useRoundScores } from '../composables/useRoundScores';
export { useRoundSummary, RoundSummaryStation, RoundSummaryData } from '../composables/useRoundSummary';
export { ROUND_DURATION_MS, STATION_DURATION_MS, useRoundTimer } from '../composables/useRoundTimer';
export { useSessionExpiry } from '../composables/useSessionExpiry';
export { clearStationMissionsProgress, useStationMissions, MissionSubmitOutcome } from '../composables/useStationMissions';
export { clearStationQuestProgress, useStationQuest } from '../composables/useStationQuest';
export { STATIONS, useStations, Station } from '../composables/useStations';
export { getCurrentYear, getAgeRangeOptions, birthYearRangeValueFor, calculateAge, calculateAgeRange, ageRangeLabel, GENDER_OPTIONS, profileSchema, ProfileSchemaOutput } from '../utils/profileSchema';
export { defineLocale, extendLocale } from '../node_modules/@nuxt/ui/dist/runtime/composables/defineLocale';
export { defineShortcuts, extractShortcuts } from '../node_modules/@nuxt/ui/dist/runtime/composables/defineShortcuts';
export { useContentSearch } from '../node_modules/@nuxt/ui/dist/runtime/composables/useContentSearch';
export { useFileUpload } from '../node_modules/@nuxt/ui/dist/runtime/composables/useFileUpload';
export { useFormField } from '../node_modules/@nuxt/ui/dist/runtime/composables/useFormField';
export { useKbd } from '../node_modules/@nuxt/ui/dist/runtime/composables/useKbd';
export { useOverlay } from '../node_modules/@nuxt/ui/dist/runtime/composables/useOverlay';
export { useResizable } from '../node_modules/@nuxt/ui/dist/runtime/composables/useResizable';
export { useScrollShadow } from '../node_modules/@nuxt/ui/dist/runtime/composables/useScrollShadow';
export { useScrollspy } from '../node_modules/@nuxt/ui/dist/runtime/composables/useScrollspy';
export { useToast } from '../node_modules/@nuxt/ui/dist/runtime/composables/useToast';
export { useTour } from '../node_modules/@nuxt/ui/dist/runtime/composables/useTour';
export { usePWA, useTransparentPwaIcon, useMaskablePwaIcon, useFaviconPwaIcon, useApplePwaIcon, useAppleSplashScreenPwaIcon } from '../node_modules/@vite-pwa/nuxt/dist/runtime/composables/index';
export { useColorMode } from '../node_modules/@nuxtjs/color-mode/dist/runtime/composables';